// Auto-generated by generateImages.cjs on 2025-09-09T00:55:54.141Z
// Do not edit manually. Re-run the script after changing files under public/images.
export const images = {
  "Branding": {
    "joaquinsantos": {
      "js_logo1_converted": "/images/Branding/joaquinsantos/js_logo1_converted.avif"
    },
    "mkjp": {
      "mk_logo1_converted_web": "/images/Branding/mkjp/mk_logo1_converted_web.avif",
      "mk_logo2_converted_web": "/images/Branding/mkjp/mk_logo2_converted_web.avif",
      "mk_logo3_converted_web": "/images/Branding/mkjp/mk_logo3_converted_web.avif"
    },
    "pausepaws": {
      "pp_logo1_converted_web": "/images/Branding/pausepaws/pp_logo1_converted_web.avif",
      "pp_logo2_converted_web": "/images/Branding/pausepaws/pp_logo2_converted_web.avif",
      "pp_pa1_converted_web": "/images/Branding/pausepaws/pp_pa1_converted_web.avif",
      "pp_pa1_mu_converted_web": "/images/Branding/pausepaws/pp_pa1_mu_converted_web.avif",
      "pp_pa2_converted_web": "/images/Branding/pausepaws/pp_pa2_converted_web.avif",
      "pp_pa2_mu_converted_web": "/images/Branding/pausepaws/pp_pa2_mu_converted_web.avif",
      "pp_pa3_converted_web": "/images/Branding/pausepaws/pp_pa3_converted_web.avif",
      "pp_pa3_mu2_converted_web": "/images/Branding/pausepaws/pp_pa3_mu2_converted_web.avif",
      "pp_pa3_mu_converted_web": "/images/Branding/pausepaws/pp_pa3_mu_converted_web.avif",
      "pp_pa4_converted_web": "/images/Branding/pausepaws/pp_pa4_converted_web.avif",
      "pp_pa5_converted_web": "/images/Branding/pausepaws/pp_pa5_converted_web.avif",
      "pp_pa5_mu_converted_web": "/images/Branding/pausepaws/pp_pa5_mu_converted_web.avif"
    },
    "tgms": {
      "tgms_mockup1_converted_web": "/images/Branding/tgms/tgms_mockup1_converted_web.avif",
      "tgms_mockup2_converted_web": "/images/Branding/tgms/tgms_mockup2_converted_web.avif"
    }
  },
  "logo": "/images/logo_web.jpeg",
  "logo_web": "/images/logo_web.jpeg",
  "Photo": {
    "capeaguilar": {
      "cda_10_converted": "/images/Photo/capeaguilar/cda_10_converted.avif",
      "cda_1_converted": "/images/Photo/capeaguilar/cda_1_converted.avif",
      "cda_2_converted": "/images/Photo/capeaguilar/cda_2_converted.avif",
      "cda_3_converted": "/images/Photo/capeaguilar/cda_3_converted.avif",
      "cda_4_converted": "/images/Photo/capeaguilar/cda_4_converted.avif",
      "cda_5_converted": "/images/Photo/capeaguilar/cda_5_converted.avif",
      "cda_6_converted": "/images/Photo/capeaguilar/cda_6_converted.avif",
      "cda_7_converted": "/images/Photo/capeaguilar/cda_7_converted.avif",
      "cda_8_converted": "/images/Photo/capeaguilar/cda_8_converted.avif",
      "cda_9_converted": "/images/Photo/capeaguilar/cda_9_converted.avif"
    },
    "casetify": {
      "casetify_airpods1_converted_web": "/images/Photo/casetify/casetify_airpods1_converted_web.avif",
      "casetify_airpods2_converted_web": "/images/Photo/casetify/casetify_airpods2_converted_web.avif"
    },
    "flowerknows": {
      "flowerk_0_converted_web": "/images/Photo/flowerknows/flowerk_0_converted_web.avif",
      "flowerk_10_converted_web": "/images/Photo/flowerknows/flowerk_10_converted_web.avif",
      "flowerk_11_converted_web": "/images/Photo/flowerknows/flowerk_11_converted_web.avif",
      "flowerk_12_converted_web": "/images/Photo/flowerknows/flowerk_12_converted_web.avif",
      "flowerk_13_converted_web": "/images/Photo/flowerknows/flowerk_13_converted_web.avif",
      "flowerk_14_converted_web": "/images/Photo/flowerknows/flowerk_14_converted_web.avif",
      "flowerk_15_converted_web": "/images/Photo/flowerknows/flowerk_15_converted_web.avif",
      "flowerk_16_converted_web": "/images/Photo/flowerknows/flowerk_16_converted_web.avif",
      "flowerk_17_converted_web": "/images/Photo/flowerknows/flowerk_17_converted_web.avif",
      "flowerk_18_converted_web": "/images/Photo/flowerknows/flowerk_18_converted_web.avif",
      "flowerk_1_converted_web": "/images/Photo/flowerknows/flowerk_1_converted_web.avif",
      "flowerk_2_converted_web": "/images/Photo/flowerknows/flowerk_2_converted_web.avif",
      "flowerk_3_converted_web": "/images/Photo/flowerknows/flowerk_3_converted_web.avif",
      "flowerk_4_converted_web": "/images/Photo/flowerknows/flowerk_4_converted_web.avif",
      "flowerk_5_converted_web": "/images/Photo/flowerknows/flowerk_5_converted_web.avif",
      "flowerk_6_converted_web": "/images/Photo/flowerknows/flowerk_6_converted_web.avif",
      "flowerk_7_converted_web": "/images/Photo/flowerknows/flowerk_7_converted_web.avif",
      "flowerk_8_converted_web": "/images/Photo/flowerknows/flowerk_8_converted_web.avif",
      "flowerk_9_converted_web": "/images/Photo/flowerknows/flowerk_9_converted_web.avif"
    },
    "foodphotog": {
      "takoyaki_1_converted_web": "/images/Photo/foodphotog/takoyaki_1_converted_web.avif"
    },
    "kristel": {
      "kristelhk_10_converted_web": "/images/Photo/kristel/kristelhk_10_converted_web.avif",
      "kristelhk_11_converted_web": "/images/Photo/kristel/kristelhk_11_converted_web.avif",
      "kristelhk_12_converted_web": "/images/Photo/kristel/kristelhk_12_converted_web.avif",
      "kristelhk_13_converted_web": "/images/Photo/kristel/kristelhk_13_converted_web.avif",
      "kristelhk_14_converted_web": "/images/Photo/kristel/kristelhk_14_converted_web.avif",
      "kristelhk_15_converted_web": "/images/Photo/kristel/kristelhk_15_converted_web.avif",
      "kristelhk_16_converted_web": "/images/Photo/kristel/kristelhk_16_converted_web.avif",
      "kristelhk_17_converted_web": "/images/Photo/kristel/kristelhk_17_converted_web.avif",
      "kristelhk_18_converted_web": "/images/Photo/kristel/kristelhk_18_converted_web.avif",
      "kristelhk_19_converted_web": "/images/Photo/kristel/kristelhk_19_converted_web.avif",
      "kristelhk_1_converted_web": "/images/Photo/kristel/kristelhk_1_converted_web.avif",
      "kristelhk_2_converted_web": "/images/Photo/kristel/kristelhk_2_converted_web.avif",
      "kristelhk_3_converted_web": "/images/Photo/kristel/kristelhk_3_converted_web.avif",
      "kristelhk_4_converted_web": "/images/Photo/kristel/kristelhk_4_converted_web.avif",
      "kristelhk_5_converted_web": "/images/Photo/kristel/kristelhk_5_converted_web.avif",
      "kristelhk_6_converted_web": "/images/Photo/kristel/kristelhk_6_converted_web.avif",
      "kristelhk_7_converted_web": "/images/Photo/kristel/kristelhk_7_converted_web.avif",
      "kristelhk_8_converted_web": "/images/Photo/kristel/kristelhk_8_converted_web.avif",
      "kristelhk_9_converted_web": "/images/Photo/kristel/kristelhk_9_converted_web.avif",
      "kristelph_1_converted_web": "/images/Photo/kristel/kristelph_1_converted_web.avif",
      "kristelph_2_converted_web": "/images/Photo/kristel/kristelph_2_converted_web.avif",
      "kristelph_3_converted_web": "/images/Photo/kristel/kristelph_3_converted_web.avif",
      "kristelph_4_converted_web": "/images/Photo/kristel/kristelph_4_converted_web.avif",
      "kristelph_5_converted_web": "/images/Photo/kristel/kristelph_5_converted_web.avif",
      "kristelval_1_converted_web": "/images/Photo/kristel/kristelval_1_converted_web.avif",
      "kristelval_2_converted_web": "/images/Photo/kristel/kristelval_2_converted_web.avif",
      "kristelval_3_converted_web": "/images/Photo/kristel/kristelval_3_converted_web.avif",
      "kristelval_4_converted_web": "/images/Photo/kristel/kristelval_4_converted_web.avif",
      "kristelval_5_converted_web": "/images/Photo/kristel/kristelval_5_converted_web.avif"
    },
    "moto": {
      "dominarph_1_converted_web": "/images/Photo/moto/dominarph_1_converted_web.avif",
      "dominarph_2_converted_web": "/images/Photo/moto/dominarph_2_converted_web.avif",
      "dominarph_3_converted_web": "/images/Photo/moto/dominarph_3_converted_web.avif",
      "hondahk_1_converted_web": "/images/Photo/moto/hondahk_1_converted_web.avif",
      "hondahk_2_converted_web": "/images/Photo/moto/hondahk_2_converted_web.avif",
      "hondaph_1_converted_web": "/images/Photo/moto/hondaph_1_converted_web.avif",
      "ra_1_converted_web": "/images/Photo/moto/ra_1_converted_web.avif",
      "ra_2_converted_web": "/images/Photo/moto/ra_2_converted_web.avif",
      "ra_3_converted_web": "/images/Photo/moto/ra_3_converted_web.avif",
      "ra_4_converted_web": "/images/Photo/moto/ra_4_converted_web.avif",
      "ra_5_converted_web": "/images/Photo/moto/ra_5_converted_web.avif",
      "triumphhk_1_converted_web": "/images/Photo/moto/triumphhk_1_converted_web.avif",
      "triumphhk_2_converted_web": "/images/Photo/moto/triumphhk_2_converted_web.avif"
    },
    "redconcept": {
      "redc_1_converted_web": "/images/Photo/redconcept/redc_1_converted_web.avif",
      "redc_2_converted_web": "/images/Photo/redconcept/redc_2_converted_web.avif",
      "redc_3_converted_web": "/images/Photo/redconcept/redc_3_converted_web.avif",
      "redc_4_converted_web": "/images/Photo/redconcept/redc_4_converted_web.avif",
      "redc_5_converted_web": "/images/Photo/redconcept/redc_5_converted_web.avif",
      "redc_6_converted_web": "/images/Photo/redconcept/redc_6_converted_web.avif"
    },
    "streethk": {
      "beachhk_1_converted_web": "/images/Photo/streethk/beachhk_1_converted_web.avif",
      "disneyhk_1_converted": "/images/Photo/streethk/disneyhk_1_converted.avif",
      "disneyhk_2_converted": "/images/Photo/streethk/disneyhk_2_converted.avif",
      "disneyhk_3_converted": "/images/Photo/streethk/disneyhk_3_converted.avif",
      "disneyhk_4_converted": "/images/Photo/streethk/disneyhk_4_converted.avif",
      "streethk_10_converted_web": "/images/Photo/streethk/streethk_10_converted_web.avif",
      "streethk_11_converted_web": "/images/Photo/streethk/streethk_11_converted_web.avif",
      "streethk_12_converted_web": "/images/Photo/streethk/streethk_12_converted_web.avif",
      "streethk_13_converted_web": "/images/Photo/streethk/streethk_13_converted_web.avif",
      "streethk_1_converted_web": "/images/Photo/streethk/streethk_1_converted_web.avif",
      "streethk_2_converted_web": "/images/Photo/streethk/streethk_2_converted_web.avif",
      "streethk_3_converted_web": "/images/Photo/streethk/streethk_3_converted_web.avif",
      "streethk_4_converted_web": "/images/Photo/streethk/streethk_4_converted_web.avif",
      "streethk_5_converted_web": "/images/Photo/streethk/streethk_5_converted_web.avif",
      "streethk_6.1_converted_web": "/images/Photo/streethk/streethk_6.1_converted_web.avif",
      "streethk_6.2_converted_web": "/images/Photo/streethk/streethk_6.2_converted_web.avif",
      "streethk_7_converted_web": "/images/Photo/streethk/streethk_7_converted_web.avif",
      "streethk_8_converted_web": "/images/Photo/streethk/streethk_8_converted_web.avif",
      "streethk_9_converted_web": "/images/Photo/streethk/streethk_9_converted_web.avif"
    },
    "tattoo": {
      "tatt_1_converted_web": "/images/Photo/tattoo/tatt_1_converted_web.avif",
      "tatt_2_converted_web": "/images/Photo/tattoo/tatt_2_converted_web.avif",
      "tatt_3_converted_web": "/images/Photo/tattoo/tatt_3_converted_web.avif"
    }
  },
  "stayelli_portrait": "/images/stayelli_portrait_web.avif",
  "stayelli_portrait_web": "/images/stayelli_portrait_web.avif",
  "ThreeD": {
    "images": {
      "Branding": {
        "joaquinsantos": {
          "js_logo1_converted": "/images/ThreeD/images/Branding/joaquinsantos/js_logo1_converted.avif"
        },
        "mkjp": {
          "mk_logo1_converted_web": "/images/ThreeD/images/Branding/mkjp/mk_logo1_converted_web.avif",
          "mk_logo2_converted_web": "/images/ThreeD/images/Branding/mkjp/mk_logo2_converted_web.avif",
          "mk_logo3_converted_web": "/images/ThreeD/images/Branding/mkjp/mk_logo3_converted_web.avif"
        },
        "pausepaws": {
          "pp_logo1_converted_web": "/images/ThreeD/images/Branding/pausepaws/pp_logo1_converted_web.avif",
          "pp_logo2_converted_web": "/images/ThreeD/images/Branding/pausepaws/pp_logo2_converted_web.avif",
          "pp_pa1_converted_web": "/images/ThreeD/images/Branding/pausepaws/pp_pa1_converted_web.avif",
          "pp_pa1_mu_converted_web": "/images/ThreeD/images/Branding/pausepaws/pp_pa1_mu_converted_web.avif",
          "pp_pa2_converted_web": "/images/ThreeD/images/Branding/pausepaws/pp_pa2_converted_web.avif",
          "pp_pa2_mu_converted_web": "/images/ThreeD/images/Branding/pausepaws/pp_pa2_mu_converted_web.avif",
          "pp_pa3_converted_web": "/images/ThreeD/images/Branding/pausepaws/pp_pa3_converted_web.avif",
          "pp_pa3_mu2_converted_web": "/images/ThreeD/images/Branding/pausepaws/pp_pa3_mu2_converted_web.avif",
          "pp_pa3_mu_converted_web": "/images/ThreeD/images/Branding/pausepaws/pp_pa3_mu_converted_web.avif",
          "pp_pa4_converted_web": "/images/ThreeD/images/Branding/pausepaws/pp_pa4_converted_web.avif",
          "pp_pa5_converted_web": "/images/ThreeD/images/Branding/pausepaws/pp_pa5_converted_web.avif",
          "pp_pa5_mu_converted_web": "/images/ThreeD/images/Branding/pausepaws/pp_pa5_mu_converted_web.avif"
        },
        "tgms": {
          "tgms_mockup1_converted_web": "/images/ThreeD/images/Branding/tgms/tgms_mockup1_converted_web.avif",
          "tgms_mockup2_converted_web": "/images/ThreeD/images/Branding/tgms/tgms_mockup2_converted_web.avif"
        }
      },
      "logo": "/images/ThreeD/images/logo_web.jpeg",
      "logo_web": "/images/ThreeD/images/logo_web.jpeg",
      "Photo": {
        "capeaguilar": {
          "cda_10_converted": "/images/ThreeD/images/Photo/capeaguilar/cda_10_converted.avif",
          "cda_1_converted": "/images/ThreeD/images/Photo/capeaguilar/cda_1_converted.avif",
          "cda_2_converted": "/images/ThreeD/images/Photo/capeaguilar/cda_2_converted.avif",
          "cda_3_converted": "/images/ThreeD/images/Photo/capeaguilar/cda_3_converted.avif",
          "cda_4_converted": "/images/ThreeD/images/Photo/capeaguilar/cda_4_converted.avif",
          "cda_5_converted": "/images/ThreeD/images/Photo/capeaguilar/cda_5_converted.avif",
          "cda_6_converted": "/images/ThreeD/images/Photo/capeaguilar/cda_6_converted.avif",
          "cda_7_converted": "/images/ThreeD/images/Photo/capeaguilar/cda_7_converted.avif",
          "cda_8_converted": "/images/ThreeD/images/Photo/capeaguilar/cda_8_converted.avif",
          "cda_9_converted": "/images/ThreeD/images/Photo/capeaguilar/cda_9_converted.avif"
        },
        "casetify": {
          "casetify_airpods1_converted_web": "/images/ThreeD/images/Photo/casetify/casetify_airpods1_converted_web.avif",
          "casetify_airpods2_converted_web": "/images/ThreeD/images/Photo/casetify/casetify_airpods2_converted_web.avif"
        },
        "flowerknows": {
          "flowerk_0_converted_web": "/images/ThreeD/images/Photo/flowerknows/flowerk_0_converted_web.avif",
          "flowerk_10_converted_web": "/images/ThreeD/images/Photo/flowerknows/flowerk_10_converted_web.avif",
          "flowerk_11_converted_web": "/images/ThreeD/images/Photo/flowerknows/flowerk_11_converted_web.avif",
          "flowerk_12_converted_web": "/images/ThreeD/images/Photo/flowerknows/flowerk_12_converted_web.avif",
          "flowerk_13_converted_web": "/images/ThreeD/images/Photo/flowerknows/flowerk_13_converted_web.avif",
          "flowerk_14_converted_web": "/images/ThreeD/images/Photo/flowerknows/flowerk_14_converted_web.avif",
          "flowerk_15_converted_web": "/images/ThreeD/images/Photo/flowerknows/flowerk_15_converted_web.avif",
          "flowerk_16_converted_web": "/images/ThreeD/images/Photo/flowerknows/flowerk_16_converted_web.avif",
          "flowerk_17_converted_web": "/images/ThreeD/images/Photo/flowerknows/flowerk_17_converted_web.avif",
          "flowerk_18_converted_web": "/images/ThreeD/images/Photo/flowerknows/flowerk_18_converted_web.avif",
          "flowerk_1_converted_web": "/images/ThreeD/images/Photo/flowerknows/flowerk_1_converted_web.avif",
          "flowerk_2_converted_web": "/images/ThreeD/images/Photo/flowerknows/flowerk_2_converted_web.avif",
          "flowerk_3_converted_web": "/images/ThreeD/images/Photo/flowerknows/flowerk_3_converted_web.avif",
          "flowerk_4_converted_web": "/images/ThreeD/images/Photo/flowerknows/flowerk_4_converted_web.avif",
          "flowerk_5_converted_web": "/images/ThreeD/images/Photo/flowerknows/flowerk_5_converted_web.avif",
          "flowerk_6_converted_web": "/images/ThreeD/images/Photo/flowerknows/flowerk_6_converted_web.avif",
          "flowerk_7_converted_web": "/images/ThreeD/images/Photo/flowerknows/flowerk_7_converted_web.avif",
          "flowerk_8_converted_web": "/images/ThreeD/images/Photo/flowerknows/flowerk_8_converted_web.avif",
          "flowerk_9_converted_web": "/images/ThreeD/images/Photo/flowerknows/flowerk_9_converted_web.avif"
        },
        "foodphotog": {
          "takoyaki_1_converted_web": "/images/ThreeD/images/Photo/foodphotog/takoyaki_1_converted_web.avif"
        },
        "kristel": {
          "kristelhk_10_converted_web": "/images/ThreeD/images/Photo/kristel/kristelhk_10_converted_web.avif",
          "kristelhk_11_converted_web": "/images/ThreeD/images/Photo/kristel/kristelhk_11_converted_web.avif",
          "kristelhk_12_converted_web": "/images/ThreeD/images/Photo/kristel/kristelhk_12_converted_web.avif",
          "kristelhk_13_converted_web": "/images/ThreeD/images/Photo/kristel/kristelhk_13_converted_web.avif",
          "kristelhk_14_converted_web": "/images/ThreeD/images/Photo/kristel/kristelhk_14_converted_web.avif",
          "kristelhk_15_converted_web": "/images/ThreeD/images/Photo/kristel/kristelhk_15_converted_web.avif",
          "kristelhk_16_converted_web": "/images/ThreeD/images/Photo/kristel/kristelhk_16_converted_web.avif",
          "kristelhk_17_converted_web": "/images/ThreeD/images/Photo/kristel/kristelhk_17_converted_web.avif",
          "kristelhk_18_converted_web": "/images/ThreeD/images/Photo/kristel/kristelhk_18_converted_web.avif",
          "kristelhk_19_converted_web": "/images/ThreeD/images/Photo/kristel/kristelhk_19_converted_web.avif",
          "kristelhk_1_converted_web": "/images/ThreeD/images/Photo/kristel/kristelhk_1_converted_web.avif",
          "kristelhk_2_converted_web": "/images/ThreeD/images/Photo/kristel/kristelhk_2_converted_web.avif",
          "kristelhk_3_converted_web": "/images/ThreeD/images/Photo/kristel/kristelhk_3_converted_web.avif",
          "kristelhk_4_converted_web": "/images/ThreeD/images/Photo/kristel/kristelhk_4_converted_web.avif",
          "kristelhk_5_converted_web": "/images/ThreeD/images/Photo/kristel/kristelhk_5_converted_web.avif",
          "kristelhk_6_converted_web": "/images/ThreeD/images/Photo/kristel/kristelhk_6_converted_web.avif",
          "kristelhk_7_converted_web": "/images/ThreeD/images/Photo/kristel/kristelhk_7_converted_web.avif",
          "kristelhk_8_converted_web": "/images/ThreeD/images/Photo/kristel/kristelhk_8_converted_web.avif",
          "kristelhk_9_converted_web": "/images/ThreeD/images/Photo/kristel/kristelhk_9_converted_web.avif",
          "kristelph_1_converted_web": "/images/ThreeD/images/Photo/kristel/kristelph_1_converted_web.avif",
          "kristelph_2_converted_web": "/images/ThreeD/images/Photo/kristel/kristelph_2_converted_web.avif",
          "kristelph_3_converted_web": "/images/ThreeD/images/Photo/kristel/kristelph_3_converted_web.avif",
          "kristelph_4_converted_web": "/images/ThreeD/images/Photo/kristel/kristelph_4_converted_web.avif",
          "kristelph_5_converted_web": "/images/ThreeD/images/Photo/kristel/kristelph_5_converted_web.avif",
          "kristelval_1_converted_web": "/images/ThreeD/images/Photo/kristel/kristelval_1_converted_web.avif",
          "kristelval_2_converted_web": "/images/ThreeD/images/Photo/kristel/kristelval_2_converted_web.avif",
          "kristelval_3_converted_web": "/images/ThreeD/images/Photo/kristel/kristelval_3_converted_web.avif",
          "kristelval_4_converted_web": "/images/ThreeD/images/Photo/kristel/kristelval_4_converted_web.avif",
          "kristelval_5_converted_web": "/images/ThreeD/images/Photo/kristel/kristelval_5_converted_web.avif"
        },
        "moto": {
          "dominarph_1_converted_web": "/images/ThreeD/images/Photo/moto/dominarph_1_converted_web.avif",
          "dominarph_2_converted_web": "/images/ThreeD/images/Photo/moto/dominarph_2_converted_web.avif",
          "dominarph_3_converted_web": "/images/ThreeD/images/Photo/moto/dominarph_3_converted_web.avif",
          "hondahk_1_converted_web": "/images/ThreeD/images/Photo/moto/hondahk_1_converted_web.avif",
          "hondahk_2_converted_web": "/images/ThreeD/images/Photo/moto/hondahk_2_converted_web.avif",
          "hondaph_1_converted_web": "/images/ThreeD/images/Photo/moto/hondaph_1_converted_web.avif",
          "ra_1_converted_web": "/images/ThreeD/images/Photo/moto/ra_1_converted_web.avif",
          "ra_2_converted_web": "/images/ThreeD/images/Photo/moto/ra_2_converted_web.avif",
          "ra_3_converted_web": "/images/ThreeD/images/Photo/moto/ra_3_converted_web.avif",
          "ra_4_converted_web": "/images/ThreeD/images/Photo/moto/ra_4_converted_web.avif",
          "ra_5_converted_web": "/images/ThreeD/images/Photo/moto/ra_5_converted_web.avif",
          "triumphhk_1_converted_web": "/images/ThreeD/images/Photo/moto/triumphhk_1_converted_web.avif",
          "triumphhk_2_converted_web": "/images/ThreeD/images/Photo/moto/triumphhk_2_converted_web.avif"
        },
        "redconcept": {
          "redc_1_converted_web": "/images/ThreeD/images/Photo/redconcept/redc_1_converted_web.avif",
          "redc_2_converted_web": "/images/ThreeD/images/Photo/redconcept/redc_2_converted_web.avif",
          "redc_3_converted_web": "/images/ThreeD/images/Photo/redconcept/redc_3_converted_web.avif",
          "redc_4_converted_web": "/images/ThreeD/images/Photo/redconcept/redc_4_converted_web.avif",
          "redc_5_converted_web": "/images/ThreeD/images/Photo/redconcept/redc_5_converted_web.avif",
          "redc_6_converted_web": "/images/ThreeD/images/Photo/redconcept/redc_6_converted_web.avif"
        },
        "streethk": {
          "beachhk_1_converted_web": "/images/ThreeD/images/Photo/streethk/beachhk_1_converted_web.avif",
          "disneyhk_1_converted": "/images/ThreeD/images/Photo/streethk/disneyhk_1_converted.avif",
          "disneyhk_2_converted": "/images/ThreeD/images/Photo/streethk/disneyhk_2_converted.avif",
          "disneyhk_3_converted": "/images/ThreeD/images/Photo/streethk/disneyhk_3_converted.avif",
          "disneyhk_4_converted": "/images/ThreeD/images/Photo/streethk/disneyhk_4_converted.avif",
          "streethk_10_converted_web": "/images/ThreeD/images/Photo/streethk/streethk_10_converted_web.avif",
          "streethk_11_converted_web": "/images/ThreeD/images/Photo/streethk/streethk_11_converted_web.avif",
          "streethk_12_converted_web": "/images/ThreeD/images/Photo/streethk/streethk_12_converted_web.avif",
          "streethk_13_converted_web": "/images/ThreeD/images/Photo/streethk/streethk_13_converted_web.avif",
          "streethk_1_converted_web": "/images/ThreeD/images/Photo/streethk/streethk_1_converted_web.avif",
          "streethk_2_converted_web": "/images/ThreeD/images/Photo/streethk/streethk_2_converted_web.avif",
          "streethk_3_converted_web": "/images/ThreeD/images/Photo/streethk/streethk_3_converted_web.avif",
          "streethk_4_converted_web": "/images/ThreeD/images/Photo/streethk/streethk_4_converted_web.avif",
          "streethk_5_converted_web": "/images/ThreeD/images/Photo/streethk/streethk_5_converted_web.avif",
          "streethk_6.1_converted_web": "/images/ThreeD/images/Photo/streethk/streethk_6.1_converted_web.avif",
          "streethk_6.2_converted_web": "/images/ThreeD/images/Photo/streethk/streethk_6.2_converted_web.avif",
          "streethk_7_converted_web": "/images/ThreeD/images/Photo/streethk/streethk_7_converted_web.avif",
          "streethk_8_converted_web": "/images/ThreeD/images/Photo/streethk/streethk_8_converted_web.avif",
          "streethk_9_converted_web": "/images/ThreeD/images/Photo/streethk/streethk_9_converted_web.avif"
        },
        "tattoo": {
          "tatt_1_converted_web": "/images/ThreeD/images/Photo/tattoo/tatt_1_converted_web.avif",
          "tatt_2_converted_web": "/images/ThreeD/images/Photo/tattoo/tatt_2_converted_web.avif",
          "tatt_3_converted_web": "/images/ThreeD/images/Photo/tattoo/tatt_3_converted_web.avif"
        }
      },
      "stayelli_portrait": "/images/ThreeD/images/stayelli_portrait_web.avif",
      "stayelli_portrait_web": "/images/ThreeD/images/stayelli_portrait_web.avif",
      "ThreeD": {
        "mod_cabinet1_converted_web": "/images/ThreeD/images/ThreeD/mod_cabinet1_converted_web.avif",
        "mod_cabinet2_converted_web": "/images/ThreeD/images/ThreeD/mod_cabinet2_converted_web.avif",
        "mod_cathode1_converted_web": "/images/ThreeD/images/ThreeD/mod_cathode1_converted_web.avif",
        "mod_cathode2_converted": "/images/ThreeD/images/ThreeD/mod_cathode2_converted.avif",
        "mod_couch1_converted_web": "/images/ThreeD/images/ThreeD/mod_couch1_converted_web.avif",
        "mod_couch2_converted_web": "/images/ThreeD/images/ThreeD/mod_couch2_converted_web.avif",
        "mod_fireplace1_converted_web": "/images/ThreeD/images/ThreeD/mod_fireplace1_converted_web.avif",
        "mod_fireplace2_converted_web": "/images/ThreeD/images/ThreeD/mod_fireplace2_converted_web.avif",
        "mod_juketable1_converted_web": "/images/ThreeD/images/ThreeD/mod_juketable1_converted_web.avif",
        "mod_juketable2_converted_web": "/images/ThreeD/images/ThreeD/mod_juketable2_converted_web.avif",
        "mod_sanc1_converted_web": "/images/ThreeD/images/ThreeD/mod_sanc1_converted_web.avif",
        "mod_sanc2_converted_web": "/images/ThreeD/images/ThreeD/mod_sanc2_converted_web.avif",
        "mod_sanc3_converted_web": "/images/ThreeD/images/ThreeD/mod_sanc3_converted_web.avif",
        "mod_sanc4_converted_web": "/images/ThreeD/images/ThreeD/mod_sanc4_converted_web.avif",
        "mod_sanc5_converted_web": "/images/ThreeD/images/ThreeD/mod_sanc5_converted_web.avif",
        "mod_sanc6_converted_web": "/images/ThreeD/images/ThreeD/mod_sanc6_converted_web.avif",
        "mod_sanc7_converted_web": "/images/ThreeD/images/ThreeD/mod_sanc7_converted_web.avif",
        "mod_sunclock1_converted_web": "/images/ThreeD/images/ThreeD/mod_sunclock1_converted_web.avif",
        "mod_sunclock2_converted": "/images/ThreeD/images/ThreeD/mod_sunclock2_converted.avif",
        "mod_winebottle_converted_web": "/images/ThreeD/images/ThreeD/mod_winebottle_converted_web.avif"
      },
      "x icon": "/images/ThreeD/images/x icon.png"
    },
    "mod_cabinet1_converted_web": "/images/ThreeD/mod_cabinet1_converted_web.avif",
    "mod_cabinet2_converted_web": "/images/ThreeD/mod_cabinet2_converted_web.avif",
    "mod_cathode1_converted_web": "/images/ThreeD/mod_cathode1_converted_web.avif",
    "mod_cathode2_converted": "/images/ThreeD/mod_cathode2_converted.avif",
    "mod_couch1_converted_web": "/images/ThreeD/mod_couch1_converted_web.avif",
    "mod_couch2_converted_web": "/images/ThreeD/mod_couch2_converted_web.avif",
    "mod_fireplace1_converted_web": "/images/ThreeD/mod_fireplace1_converted_web.avif",
    "mod_fireplace2_converted_web": "/images/ThreeD/mod_fireplace2_converted_web.avif",
    "mod_juketable1_converted_web": "/images/ThreeD/mod_juketable1_converted_web.avif",
    "mod_juketable2_converted_web": "/images/ThreeD/mod_juketable2_converted_web.avif",
    "mod_sanc1_converted_web": "/images/ThreeD/mod_sanc1_converted_web.avif",
    "mod_sanc2_converted_web": "/images/ThreeD/mod_sanc2_converted_web.avif",
    "mod_sanc3_converted_web": "/images/ThreeD/mod_sanc3_converted_web.avif",
    "mod_sanc4_converted_web": "/images/ThreeD/mod_sanc4_converted_web.avif",
    "mod_sanc5_converted_web": "/images/ThreeD/mod_sanc5_converted_web.avif",
    "mod_sanc6_converted_web": "/images/ThreeD/mod_sanc6_converted_web.avif",
    "mod_sanc7_converted_web": "/images/ThreeD/mod_sanc7_converted_web.avif",
    "mod_sunclock1_converted_web": "/images/ThreeD/mod_sunclock1_converted_web.avif",
    "mod_sunclock2_converted": "/images/ThreeD/mod_sunclock2_converted.avif",
    "mod_winebottle_converted_web": "/images/ThreeD/mod_winebottle_converted_web.avif"
  },
  "x icon": "/images/x icon.png"
} as const;
export type ImagesMap = typeof images;

export const BrandingJoaquinsantos = [
  "/images/Branding/joaquinsantos/js_logo1_converted.avif"
] as const;
export const BrandingMkjp = [
  "/images/Branding/mkjp/mk_logo1_converted_web.avif",
  "/images/Branding/mkjp/mk_logo2_converted_web.avif",
  "/images/Branding/mkjp/mk_logo3_converted_web.avif"
] as const;
export const BrandingPausepaws = [
  "/images/Branding/pausepaws/pp_logo1_converted_web.avif",
  "/images/Branding/pausepaws/pp_logo2_converted_web.avif",
  "/images/Branding/pausepaws/pp_pa1_converted_web.avif",
  "/images/Branding/pausepaws/pp_pa1_mu_converted_web.avif",
  "/images/Branding/pausepaws/pp_pa2_converted_web.avif",
  "/images/Branding/pausepaws/pp_pa2_mu_converted_web.avif",
  "/images/Branding/pausepaws/pp_pa3_converted_web.avif",
  "/images/Branding/pausepaws/pp_pa3_mu2_converted_web.avif",
  "/images/Branding/pausepaws/pp_pa3_mu_converted_web.avif",
  "/images/Branding/pausepaws/pp_pa4_converted_web.avif",
  "/images/Branding/pausepaws/pp_pa5_converted_web.avif",
  "/images/Branding/pausepaws/pp_pa5_mu_converted_web.avif"
] as const;
export const BrandingTgms = [
  "/images/Branding/tgms/tgms_mockup1_converted_web.avif",
  "/images/Branding/tgms/tgms_mockup2_converted_web.avif"
] as const;
export const PhotoCapeaguilar = [
  "/images/Photo/capeaguilar/cda_10_converted.avif",
  "/images/Photo/capeaguilar/cda_1_converted.avif",
  "/images/Photo/capeaguilar/cda_2_converted.avif",
  "/images/Photo/capeaguilar/cda_3_converted.avif",
  "/images/Photo/capeaguilar/cda_4_converted.avif",
  "/images/Photo/capeaguilar/cda_5_converted.avif",
  "/images/Photo/capeaguilar/cda_6_converted.avif",
  "/images/Photo/capeaguilar/cda_7_converted.avif",
  "/images/Photo/capeaguilar/cda_8_converted.avif",
  "/images/Photo/capeaguilar/cda_9_converted.avif"
] as const;
export const PhotoCasetify = [
  "/images/Photo/casetify/casetify_airpods1_converted_web.avif",
  "/images/Photo/casetify/casetify_airpods2_converted_web.avif"
] as const;
export const PhotoFlowerknows = [
  "/images/Photo/flowerknows/flowerk_0_converted_web.avif",
  "/images/Photo/flowerknows/flowerk_10_converted_web.avif",
  "/images/Photo/flowerknows/flowerk_11_converted_web.avif",
  "/images/Photo/flowerknows/flowerk_12_converted_web.avif",
  "/images/Photo/flowerknows/flowerk_13_converted_web.avif",
  "/images/Photo/flowerknows/flowerk_14_converted_web.avif",
  "/images/Photo/flowerknows/flowerk_15_converted_web.avif",
  "/images/Photo/flowerknows/flowerk_16_converted_web.avif",
  "/images/Photo/flowerknows/flowerk_17_converted_web.avif",
  "/images/Photo/flowerknows/flowerk_18_converted_web.avif",
  "/images/Photo/flowerknows/flowerk_1_converted_web.avif",
  "/images/Photo/flowerknows/flowerk_2_converted_web.avif",
  "/images/Photo/flowerknows/flowerk_3_converted_web.avif",
  "/images/Photo/flowerknows/flowerk_4_converted_web.avif",
  "/images/Photo/flowerknows/flowerk_5_converted_web.avif",
  "/images/Photo/flowerknows/flowerk_6_converted_web.avif",
  "/images/Photo/flowerknows/flowerk_7_converted_web.avif",
  "/images/Photo/flowerknows/flowerk_8_converted_web.avif",
  "/images/Photo/flowerknows/flowerk_9_converted_web.avif"
] as const;
export const PhotoFoodphotog = [
  "/images/Photo/foodphotog/takoyaki_1_converted_web.avif"
] as const;
export const PhotoKristel = [
  "/images/Photo/kristel/kristelhk_10_converted_web.avif",
  "/images/Photo/kristel/kristelhk_11_converted_web.avif",
  "/images/Photo/kristel/kristelhk_12_converted_web.avif",
  "/images/Photo/kristel/kristelhk_13_converted_web.avif",
  "/images/Photo/kristel/kristelhk_14_converted_web.avif",
  "/images/Photo/kristel/kristelhk_15_converted_web.avif",
  "/images/Photo/kristel/kristelhk_16_converted_web.avif",
  "/images/Photo/kristel/kristelhk_17_converted_web.avif",
  "/images/Photo/kristel/kristelhk_18_converted_web.avif",
  "/images/Photo/kristel/kristelhk_19_converted_web.avif",
  "/images/Photo/kristel/kristelhk_1_converted_web.avif",
  "/images/Photo/kristel/kristelhk_2_converted_web.avif",
  "/images/Photo/kristel/kristelhk_3_converted_web.avif",
  "/images/Photo/kristel/kristelhk_4_converted_web.avif",
  "/images/Photo/kristel/kristelhk_5_converted_web.avif",
  "/images/Photo/kristel/kristelhk_6_converted_web.avif",
  "/images/Photo/kristel/kristelhk_7_converted_web.avif",
  "/images/Photo/kristel/kristelhk_8_converted_web.avif",
  "/images/Photo/kristel/kristelhk_9_converted_web.avif",
  "/images/Photo/kristel/kristelph_1_converted_web.avif",
  "/images/Photo/kristel/kristelph_2_converted_web.avif",
  "/images/Photo/kristel/kristelph_3_converted_web.avif",
  "/images/Photo/kristel/kristelph_4_converted_web.avif",
  "/images/Photo/kristel/kristelph_5_converted_web.avif",
  "/images/Photo/kristel/kristelval_1_converted_web.avif",
  "/images/Photo/kristel/kristelval_2_converted_web.avif",
  "/images/Photo/kristel/kristelval_3_converted_web.avif",
  "/images/Photo/kristel/kristelval_4_converted_web.avif",
  "/images/Photo/kristel/kristelval_5_converted_web.avif"
] as const;
export const PhotoMoto = [
  "/images/Photo/moto/dominarph_1_converted_web.avif",
  "/images/Photo/moto/dominarph_2_converted_web.avif",
  "/images/Photo/moto/dominarph_3_converted_web.avif",
  "/images/Photo/moto/hondahk_1_converted_web.avif",
  "/images/Photo/moto/hondahk_2_converted_web.avif",
  "/images/Photo/moto/hondaph_1_converted_web.avif",
  "/images/Photo/moto/ra_1_converted_web.avif",
  "/images/Photo/moto/ra_2_converted_web.avif",
  "/images/Photo/moto/ra_3_converted_web.avif",
  "/images/Photo/moto/ra_4_converted_web.avif",
  "/images/Photo/moto/ra_5_converted_web.avif",
  "/images/Photo/moto/triumphhk_1_converted_web.avif",
  "/images/Photo/moto/triumphhk_2_converted_web.avif"
] as const;
export const PhotoRedconcept = [
  "/images/Photo/redconcept/redc_1_converted_web.avif",
  "/images/Photo/redconcept/redc_2_converted_web.avif",
  "/images/Photo/redconcept/redc_3_converted_web.avif",
  "/images/Photo/redconcept/redc_4_converted_web.avif",
  "/images/Photo/redconcept/redc_5_converted_web.avif",
  "/images/Photo/redconcept/redc_6_converted_web.avif"
] as const;
export const PhotoStreethk = [
  "/images/Photo/streethk/beachhk_1_converted_web.avif",
  "/images/Photo/streethk/disneyhk_1_converted.avif",
  "/images/Photo/streethk/disneyhk_2_converted.avif",
  "/images/Photo/streethk/disneyhk_3_converted.avif",
  "/images/Photo/streethk/disneyhk_4_converted.avif",
  "/images/Photo/streethk/streethk_10_converted_web.avif",
  "/images/Photo/streethk/streethk_11_converted_web.avif",
  "/images/Photo/streethk/streethk_12_converted_web.avif",
  "/images/Photo/streethk/streethk_13_converted_web.avif",
  "/images/Photo/streethk/streethk_1_converted_web.avif",
  "/images/Photo/streethk/streethk_2_converted_web.avif",
  "/images/Photo/streethk/streethk_3_converted_web.avif",
  "/images/Photo/streethk/streethk_4_converted_web.avif",
  "/images/Photo/streethk/streethk_5_converted_web.avif",
  "/images/Photo/streethk/streethk_6.1_converted_web.avif",
  "/images/Photo/streethk/streethk_6.2_converted_web.avif",
  "/images/Photo/streethk/streethk_7_converted_web.avif",
  "/images/Photo/streethk/streethk_8_converted_web.avif",
  "/images/Photo/streethk/streethk_9_converted_web.avif"
] as const;
export const PhotoTattoo = [
  "/images/Photo/tattoo/tatt_1_converted_web.avif",
  "/images/Photo/tattoo/tatt_2_converted_web.avif",
  "/images/Photo/tattoo/tatt_3_converted_web.avif"
] as const;
export const ThreeDImagesBrandingJoaquinsantos = [
  "/images/ThreeD/images/Branding/joaquinsantos/js_logo1_converted.avif"
] as const;
export const ThreeDImagesBrandingMkjp = [
  "/images/ThreeD/images/Branding/mkjp/mk_logo1_converted_web.avif",
  "/images/ThreeD/images/Branding/mkjp/mk_logo2_converted_web.avif",
  "/images/ThreeD/images/Branding/mkjp/mk_logo3_converted_web.avif"
] as const;
export const ThreeDImagesBrandingPausepaws = [
  "/images/ThreeD/images/Branding/pausepaws/pp_logo1_converted_web.avif",
  "/images/ThreeD/images/Branding/pausepaws/pp_logo2_converted_web.avif",
  "/images/ThreeD/images/Branding/pausepaws/pp_pa1_converted_web.avif",
  "/images/ThreeD/images/Branding/pausepaws/pp_pa1_mu_converted_web.avif",
  "/images/ThreeD/images/Branding/pausepaws/pp_pa2_converted_web.avif",
  "/images/ThreeD/images/Branding/pausepaws/pp_pa2_mu_converted_web.avif",
  "/images/ThreeD/images/Branding/pausepaws/pp_pa3_converted_web.avif",
  "/images/ThreeD/images/Branding/pausepaws/pp_pa3_mu2_converted_web.avif",
  "/images/ThreeD/images/Branding/pausepaws/pp_pa3_mu_converted_web.avif",
  "/images/ThreeD/images/Branding/pausepaws/pp_pa4_converted_web.avif",
  "/images/ThreeD/images/Branding/pausepaws/pp_pa5_converted_web.avif",
  "/images/ThreeD/images/Branding/pausepaws/pp_pa5_mu_converted_web.avif"
] as const;
export const ThreeDImagesBrandingTgms = [
  "/images/ThreeD/images/Branding/tgms/tgms_mockup1_converted_web.avif",
  "/images/ThreeD/images/Branding/tgms/tgms_mockup2_converted_web.avif"
] as const;
export const ThreeDImagesPhotoCapeaguilar = [
  "/images/ThreeD/images/Photo/capeaguilar/cda_10_converted.avif",
  "/images/ThreeD/images/Photo/capeaguilar/cda_1_converted.avif",
  "/images/ThreeD/images/Photo/capeaguilar/cda_2_converted.avif",
  "/images/ThreeD/images/Photo/capeaguilar/cda_3_converted.avif",
  "/images/ThreeD/images/Photo/capeaguilar/cda_4_converted.avif",
  "/images/ThreeD/images/Photo/capeaguilar/cda_5_converted.avif",
  "/images/ThreeD/images/Photo/capeaguilar/cda_6_converted.avif",
  "/images/ThreeD/images/Photo/capeaguilar/cda_7_converted.avif",
  "/images/ThreeD/images/Photo/capeaguilar/cda_8_converted.avif",
  "/images/ThreeD/images/Photo/capeaguilar/cda_9_converted.avif"
] as const;
export const ThreeDImagesPhotoCasetify = [
  "/images/ThreeD/images/Photo/casetify/casetify_airpods1_converted_web.avif",
  "/images/ThreeD/images/Photo/casetify/casetify_airpods2_converted_web.avif"
] as const;
export const ThreeDImagesPhotoFlowerknows = [
  "/images/ThreeD/images/Photo/flowerknows/flowerk_0_converted_web.avif",
  "/images/ThreeD/images/Photo/flowerknows/flowerk_10_converted_web.avif",
  "/images/ThreeD/images/Photo/flowerknows/flowerk_11_converted_web.avif",
  "/images/ThreeD/images/Photo/flowerknows/flowerk_12_converted_web.avif",
  "/images/ThreeD/images/Photo/flowerknows/flowerk_13_converted_web.avif",
  "/images/ThreeD/images/Photo/flowerknows/flowerk_14_converted_web.avif",
  "/images/ThreeD/images/Photo/flowerknows/flowerk_15_converted_web.avif",
  "/images/ThreeD/images/Photo/flowerknows/flowerk_16_converted_web.avif",
  "/images/ThreeD/images/Photo/flowerknows/flowerk_17_converted_web.avif",
  "/images/ThreeD/images/Photo/flowerknows/flowerk_18_converted_web.avif",
  "/images/ThreeD/images/Photo/flowerknows/flowerk_1_converted_web.avif",
  "/images/ThreeD/images/Photo/flowerknows/flowerk_2_converted_web.avif",
  "/images/ThreeD/images/Photo/flowerknows/flowerk_3_converted_web.avif",
  "/images/ThreeD/images/Photo/flowerknows/flowerk_4_converted_web.avif",
  "/images/ThreeD/images/Photo/flowerknows/flowerk_5_converted_web.avif",
  "/images/ThreeD/images/Photo/flowerknows/flowerk_6_converted_web.avif",
  "/images/ThreeD/images/Photo/flowerknows/flowerk_7_converted_web.avif",
  "/images/ThreeD/images/Photo/flowerknows/flowerk_8_converted_web.avif",
  "/images/ThreeD/images/Photo/flowerknows/flowerk_9_converted_web.avif"
] as const;
export const ThreeDImagesPhotoFoodphotog = [
  "/images/ThreeD/images/Photo/foodphotog/takoyaki_1_converted_web.avif"
] as const;
export const ThreeDImagesPhotoKristel = [
  "/images/ThreeD/images/Photo/kristel/kristelhk_10_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelhk_11_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelhk_12_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelhk_13_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelhk_14_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelhk_15_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelhk_16_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelhk_17_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelhk_18_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelhk_19_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelhk_1_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelhk_2_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelhk_3_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelhk_4_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelhk_5_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelhk_6_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelhk_7_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelhk_8_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelhk_9_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelph_1_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelph_2_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelph_3_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelph_4_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelph_5_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelval_1_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelval_2_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelval_3_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelval_4_converted_web.avif",
  "/images/ThreeD/images/Photo/kristel/kristelval_5_converted_web.avif"
] as const;
export const ThreeDImagesPhotoMoto = [
  "/images/ThreeD/images/Photo/moto/dominarph_1_converted_web.avif",
  "/images/ThreeD/images/Photo/moto/dominarph_2_converted_web.avif",
  "/images/ThreeD/images/Photo/moto/dominarph_3_converted_web.avif",
  "/images/ThreeD/images/Photo/moto/hondahk_1_converted_web.avif",
  "/images/ThreeD/images/Photo/moto/hondahk_2_converted_web.avif",
  "/images/ThreeD/images/Photo/moto/hondaph_1_converted_web.avif",
  "/images/ThreeD/images/Photo/moto/ra_1_converted_web.avif",
  "/images/ThreeD/images/Photo/moto/ra_2_converted_web.avif",
  "/images/ThreeD/images/Photo/moto/ra_3_converted_web.avif",
  "/images/ThreeD/images/Photo/moto/ra_4_converted_web.avif",
  "/images/ThreeD/images/Photo/moto/ra_5_converted_web.avif",
  "/images/ThreeD/images/Photo/moto/triumphhk_1_converted_web.avif",
  "/images/ThreeD/images/Photo/moto/triumphhk_2_converted_web.avif"
] as const;
export const ThreeDImagesPhotoRedconcept = [
  "/images/ThreeD/images/Photo/redconcept/redc_1_converted_web.avif",
  "/images/ThreeD/images/Photo/redconcept/redc_2_converted_web.avif",
  "/images/ThreeD/images/Photo/redconcept/redc_3_converted_web.avif",
  "/images/ThreeD/images/Photo/redconcept/redc_4_converted_web.avif",
  "/images/ThreeD/images/Photo/redconcept/redc_5_converted_web.avif",
  "/images/ThreeD/images/Photo/redconcept/redc_6_converted_web.avif"
] as const;
export const ThreeDImagesPhotoStreethk = [
  "/images/ThreeD/images/Photo/streethk/beachhk_1_converted_web.avif",
  "/images/ThreeD/images/Photo/streethk/disneyhk_1_converted.avif",
  "/images/ThreeD/images/Photo/streethk/disneyhk_2_converted.avif",
  "/images/ThreeD/images/Photo/streethk/disneyhk_3_converted.avif",
  "/images/ThreeD/images/Photo/streethk/disneyhk_4_converted.avif",
  "/images/ThreeD/images/Photo/streethk/streethk_10_converted_web.avif",
  "/images/ThreeD/images/Photo/streethk/streethk_11_converted_web.avif",
  "/images/ThreeD/images/Photo/streethk/streethk_12_converted_web.avif",
  "/images/ThreeD/images/Photo/streethk/streethk_13_converted_web.avif",
  "/images/ThreeD/images/Photo/streethk/streethk_1_converted_web.avif",
  "/images/ThreeD/images/Photo/streethk/streethk_2_converted_web.avif",
  "/images/ThreeD/images/Photo/streethk/streethk_3_converted_web.avif",
  "/images/ThreeD/images/Photo/streethk/streethk_4_converted_web.avif",
  "/images/ThreeD/images/Photo/streethk/streethk_5_converted_web.avif",
  "/images/ThreeD/images/Photo/streethk/streethk_6.1_converted_web.avif",
  "/images/ThreeD/images/Photo/streethk/streethk_6.2_converted_web.avif",
  "/images/ThreeD/images/Photo/streethk/streethk_7_converted_web.avif",
  "/images/ThreeD/images/Photo/streethk/streethk_8_converted_web.avif",
  "/images/ThreeD/images/Photo/streethk/streethk_9_converted_web.avif"
] as const;
export const ThreeDImagesPhotoTattoo = [
  "/images/ThreeD/images/Photo/tattoo/tatt_1_converted_web.avif",
  "/images/ThreeD/images/Photo/tattoo/tatt_2_converted_web.avif",
  "/images/ThreeD/images/Photo/tattoo/tatt_3_converted_web.avif"
] as const;
export const ThreeDImagesThreeD = [
  "/images/ThreeD/images/ThreeD/mod_cabinet1_converted_web.avif",
  "/images/ThreeD/images/ThreeD/mod_cabinet2_converted_web.avif",
  "/images/ThreeD/images/ThreeD/mod_cathode1_converted_web.avif",
  "/images/ThreeD/images/ThreeD/mod_cathode2_converted.avif",
  "/images/ThreeD/images/ThreeD/mod_couch1_converted_web.avif",
  "/images/ThreeD/images/ThreeD/mod_couch2_converted_web.avif",
  "/images/ThreeD/images/ThreeD/mod_fireplace1_converted_web.avif",
  "/images/ThreeD/images/ThreeD/mod_fireplace2_converted_web.avif",
  "/images/ThreeD/images/ThreeD/mod_juketable1_converted_web.avif",
  "/images/ThreeD/images/ThreeD/mod_juketable2_converted_web.avif",
  "/images/ThreeD/images/ThreeD/mod_sanc1_converted_web.avif",
  "/images/ThreeD/images/ThreeD/mod_sanc2_converted_web.avif",
  "/images/ThreeD/images/ThreeD/mod_sanc3_converted_web.avif",
  "/images/ThreeD/images/ThreeD/mod_sanc4_converted_web.avif",
  "/images/ThreeD/images/ThreeD/mod_sanc5_converted_web.avif",
  "/images/ThreeD/images/ThreeD/mod_sanc6_converted_web.avif",
  "/images/ThreeD/images/ThreeD/mod_sanc7_converted_web.avif",
  "/images/ThreeD/images/ThreeD/mod_sunclock1_converted_web.avif",
  "/images/ThreeD/images/ThreeD/mod_sunclock2_converted.avif",
  "/images/ThreeD/images/ThreeD/mod_winebottle_converted_web.avif"
] as const;
export const ThreeDImages = [
  "/images/ThreeD/images/logo_web.jpeg",
  "/images/ThreeD/images/logo_web.jpeg",
  "/images/ThreeD/images/stayelli_portrait_web.avif",
  "/images/ThreeD/images/stayelli_portrait_web.avif",
  "/images/ThreeD/images/x icon.png"
] as const;
export const ThreeD = [
  "/images/ThreeD/mod_cabinet1_converted_web.avif",
  "/images/ThreeD/mod_cabinet2_converted_web.avif",
  "/images/ThreeD/mod_cathode1_converted_web.avif",
  "/images/ThreeD/mod_cathode2_converted.avif",
  "/images/ThreeD/mod_couch1_converted_web.avif",
  "/images/ThreeD/mod_couch2_converted_web.avif",
  "/images/ThreeD/mod_fireplace1_converted_web.avif",
  "/images/ThreeD/mod_fireplace2_converted_web.avif",
  "/images/ThreeD/mod_juketable1_converted_web.avif",
  "/images/ThreeD/mod_juketable2_converted_web.avif",
  "/images/ThreeD/mod_sanc1_converted_web.avif",
  "/images/ThreeD/mod_sanc2_converted_web.avif",
  "/images/ThreeD/mod_sanc3_converted_web.avif",
  "/images/ThreeD/mod_sanc4_converted_web.avif",
  "/images/ThreeD/mod_sanc5_converted_web.avif",
  "/images/ThreeD/mod_sanc6_converted_web.avif",
  "/images/ThreeD/mod_sanc7_converted_web.avif",
  "/images/ThreeD/mod_sunclock1_converted_web.avif",
  "/images/ThreeD/mod_sunclock2_converted.avif",
  "/images/ThreeD/mod_winebottle_converted_web.avif"
] as const;
